Factory pattern
Andre-s-Internship/Design-Patterns pull request #2
Opened 2023-06-30 10:04 UTC by icarus-77

2023-06-30 10:32 UTC, achogrid requested changes

2023-06-30 10:32 UTC, achogrid commented on .gitignore
In general .idea folder is specific to intellij, and we should not be pushing it to remote repository. You can add it in gitignore and prevent it from pushing

2023-06-30 10:34 UTC, icarus-77 commented on .gitignore
Okay, so for the base project push only pom.xml right?

2023-07-03 07:07 UTC, achogrid commented on .gitignore
hmmm, no, actually everything except .idea

2023-07-04 10:35 UTC, merged